# supabase/config.toml

# This file is for local development configuration and to identify the project root for the Supabase CLI.
# Deployments to your self-hosted instance on Coolify are managed via environment variables, not this file.

[api]
port = 54321
# schemas = ["public", "storage", "graphql"] # Keep commented out for simplicity unless needed
# extra_schemas = ["extensions"]

[db]
port = 54322
# major_version = 15 # Keep commented out unless you have a specific local Postgres version

[studio]
port = 54323