import { InvoiceData, InvoiceTemplateInfo, InvoiceTemplateProps, PlanData, CustomizationState } from './types.ts';
import { MinimalistTemplate } from './features/invoice/templates/MinimalistTemplate.tsx';
import { ModernTemplate } from './features/invoice/templates/ModernTemplate.tsx';
import { CreativeTemplate } from './features/invoice/templates/CreativeTemplate.tsx';
import { CorporateTemplate } from './features/invoice/templates/CorporateTemplate.tsx';
import { TechTemplate } from './features/invoice/templates/TechTemplate.tsx';
import { ElegantTemplate } from './features/invoice/templates/ElegantTemplate.tsx';
import { NatureHarmonyTemplate } from './features/invoice/templates/NatureHarmonyTemplate.tsx';
import { GeometricPulseTemplate } from './features/invoice/templates/GeometricPulseTemplate.tsx';
import { VintageScrollTemplate } from './features/invoice/templates/VintageScrollTemplate.tsx';
import { CosmicFlowTemplate } from './features/invoice/templates/CosmicFlowTemplate.tsx';
import { ArtDecoTemplate } from './features/invoice/templates/ArtDecoTemplate.tsx';
import { RusticCharmTemplate } from './features/invoice/templates/RusticCharmTemplate.tsx';
import { WatercolorWashTemplate } from './features/invoice/templates/WatercolorWashTemplate.tsx';
import { MonochromeFocusTemplate } from './features/invoice/templates/MonochromeFocusTemplate.tsx';
import { IndustrialGritTemplate } from './features/invoice/templates/IndustrialGritTemplate.tsx';
import { BohemianDreamTemplate } from './features/invoice/templates/BohemianDreamTemplate.tsx';
import { RetroPixelTemplate } from './features/invoice/templates/RetroPixelTemplate.tsx';
import { LuxuryGoldTemplate } from './features/invoice/templates/LuxuryGoldTemplate.tsx';
import { CustomTemplate } from './features/invoice/templates/CustomTemplate.tsx';
import { SwissModernTemplate } from './features/invoice/templates/SwissModernTemplate.tsx';
import { HandDrawnSketchTemplate } from './features/invoice/templates/HandDrawnSketchTemplate.tsx';
import { FloralBotanicalTemplate } from './features/invoice/templates/FloralBotanicalTemplate.tsx';
import { CyberpunkGlitchTemplate } from './features/invoice/templates/CyberpunkGlitchTemplate.tsx';

// ADMIN_EMAIL is no longer used for client-side admin role simulation. Role is checked via user_metadata.
// export const ADMIN_EMAIL = 'admin@invoicemaker.linkfc.com'; 

export const DEFAULT_CURRENCY = 'USD';

export const PLANS_DATA: PlanData[] = [
  {
    id: 'free_tier',
    name: 'Free',
    price: '0',
    price_suffix: '',
    billing_cycle: 'monthly',
    features: [
      '10 invoices/month',
      '10 clients',
      '10 products',
      'Basic templates',
      'Branding on invoices',
      'No team collaboration',
      'No advanced reporting',
      'No API access',
    ],
    cta_text: 'Current Plan',
    is_current: true,
    variant: 'secondary',
    has_branding: true,
    sort_order: 1,
    invoice_limit: 10,
    client_limit: 10,
    product_limit: 10,
    team_member_limit: 1,
    api_access: false,
    advanced_reports: false,
    premium_templates: false,
  },
  {
    id: 'starter_monthly',
    name: 'Starter',
    price: '5',
    price_suffix: '/mo',
    billing_cycle: 'monthly',
    features: [
      'Unlimited invoices',
      'Unlimited clients',
      'Unlimited products',
      'All templates included',
      'Remove our branding',
      'Email support',
    ],
    cta_text: 'Choose Starter',
    is_current: false,
    variant: 'secondary',
    has_branding: false,
    sort_order: 2,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 1,
    api_access: false,
    advanced_reports: false,
    premium_templates: true,
  },
  {
    id: 'starter_annually',
    name: 'Starter',
    price: '50',
    price_suffix: '/yr',
    billing_cycle: 'annually',
    features: [
      'Unlimited invoices',
      'Unlimited clients',
      'Unlimited products',
      'All templates included',
      'Remove our branding',
      'Email support',
    ],
    cta_text: 'Choose Starter',
    is_current: false,
    variant: 'secondary',
    has_branding: false,
    sort_order: 2,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 1,
    api_access: false,
    advanced_reports: false,
    premium_templates: true,
  },
    {
    id: 'starter_monthly_inr',
    name: 'Starter',
    price: '299',
    price_suffix: '/mo',
    billing_cycle: 'monthly',
    features: [
      'Unlimited invoices',
      'Unlimited clients',
      'Unlimited products',
      'All templates included',
      'Remove our branding',
      'Email support',
    ],
    cta_text: 'Choose Starter',
    is_current: false,
    variant: 'secondary',
    has_branding: false,
    sort_order: 2,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 1,
    api_access: false,
    advanced_reports: false,
    premium_templates: true,
  },
  {
    id: 'starter_annually_inr',
    name: 'Starter',
    price: '2999',
    price_suffix: '/yr',
    billing_cycle: 'annually',
    features: [
      'Unlimited invoices',
      'Unlimited clients',
      'Unlimited products',
      'All templates included',
      'Remove our branding',
      'Email support',
    ],
    cta_text: 'Choose Starter',
    is_current: false,
    variant: 'secondary',
    has_branding: false,
    sort_order: 2,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 1,
    api_access: false,
    advanced_reports: false,
    premium_templates: true,
  },
  {
    id: 'pro_monthly',
    name: 'Pro',
    price: '15',
    price_suffix: '/mo',
    billing_cycle: 'monthly',
    features: [
        'All Starter features',
        'Up to 5 team members',
        'Advanced reporting',
        'API access for integrations',
        'Priority support',
    ],
    cta_text: 'Choose Pro',
    is_current: false,
    variant: 'primary',
    has_branding: false,
    sort_order: 3,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 5,
    api_access: true,
    advanced_reports: true,
    premium_templates: true,
  },
  {
    id: 'pro_annually',
    name: 'Pro',
    price: '150',
    price_suffix: '/yr',
    billing_cycle: 'annually',
    features: [
        'All Starter features',
        'Up to 5 team members',
        'Advanced reporting',
        'API access for integrations',
        'Priority support',
    ],
    cta_text: 'Choose Pro',
    is_current: false,
    variant: 'primary',
    has_branding: false,
    sort_order: 3,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 5,
    api_access: true,
    advanced_reports: true,
    premium_templates: true,
  },
  {
    id: 'pro_monthly_inr',
    name: 'Pro',
    price: '899',
    price_suffix: '/mo',
    billing_cycle: 'monthly',
    features: [
        'All Starter features',
        'Up to 5 team members',
        'Advanced reporting',
        'API access for integrations',
        'Priority support',
    ],
    cta_text: 'Choose Pro',
    is_current: false,
    variant: 'primary',
    has_branding: false,
    sort_order: 3,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 5,
    api_access: true,
    advanced_reports: true,
    premium_templates: true,
  },
  {
    id: 'pro_annually_inr',
    name: 'Pro',
    price: '8999',
    price_suffix: '/yr',
    billing_cycle: 'annually',
    features: [
        'All Starter features',
        'Up to 5 team members',
        'Advanced reporting',
        'API access for integrations',
        'Priority support',
    ],
    cta_text: 'Choose Pro',
    is_current: false,
    variant: 'primary',
    has_branding: false,
    sort_order: 3,
    invoice_limit: null,
    client_limit: null,
    product_limit: null,
    team_member_limit: 5,
    api_access: true,
    advanced_reports: true,
    premium_templates: true,
  },
];


export const INITIAL_CUSTOMIZATION_STATE: CustomizationState = {
  primaryColor: '#3B82F6',   // blue-500
  accentColor: '#10B981',    // emerald-500
  textColor: '#1E293B',      // slate-800
  backgroundColor: '#F8FAFC', // slate-50
  headingFont: 'Playfair Display',
  bodyFont: 'Lato',
  logoSize: 80,
  showLogo: true,
  showNotes: true,
  showTerms: true,
};

export const AVAILABLE_FONTS = [
  { family: 'Inter', label: 'Inter (Sans-Serif)' },
  { family: 'Playfair Display', label: 'Playfair Display (Serif)' },
  { family: 'Lato', label: 'Lato (Sans-Serif)' },
  { family: 'Lora', label: 'Lora (Serif)' },
  { family: 'Roboto Condensed', label: 'Roboto Condensed (Sans-Serif)' },
  { family: 'Quicksand', label: 'Quicksand (Sans-Serif)' },
  { family: 'Gochi Hand', label: 'Gochi Hand (Handwritten)' },
  { family: 'VT323', label: 'VT323 (Pixel)' },
  { family: 'Press Start 2P', label: 'Press Start 2P (Pixel)' },
  { family: 'Satisfy', label: 'Satisfy (Cursive)' },
];


export const INITIAL_INVOICE_STATE: InvoiceData = {
  id: `INV-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 10000)).padStart(4, '0')}`,
  date: new Date().toISOString().split('T')[0],
  dueDate: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString().split('T')[0],
  sender: { name: 'Your Company LLC', address: '123 Main St, Anytown, USA', email: 'your@company.com', phone: '555-1234', logoUrl: '' },
  recipient: { name: 'Client Company Inc.', address: '456 Client Ave, Otherville, USA', email: 'client@example.com', phone: '555-5678' },
  items: [{ id: crypto.randomUUID(), description: 'Sample Item or Service', quantity: 1, unitPrice: 100 }],
  notes: 'Thank you for your business!',
  terms: 'Payment due within 30 days.',
  taxes: [],
  discount: { type: 'percentage' as 'percentage' | 'fixed', value: 0 },
  currency: DEFAULT_CURRENCY,
  selectedTemplateId: 'modern', 
  manualPaymentLink: '',
  is_public: false,
  upiId: '',
  customization: INITIAL_CUSTOMIZATION_STATE,
  type: 'invoice',
  status: 'draft',
};

export const AVAILABLE_TEMPLATES: InvoiceTemplateInfo[] = [
  {
    id: 'modern',
    name: 'Modern Clean',
    description: 'A sleek and professional design with clear typography and primary color accents.',
    component: ModernTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/modern/300/200',
    isPremium: false,
  },
  {
    id: 'minimalist',
    name: 'Classic Minimalist',
    description: 'A timeless, simple, and elegant black & white design focused on readability.',
    component: MinimalistTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/minimalist/300/200',
    isPremium: false,
  },
  {
    id: 'creative',
    name: 'Creative Splash',
    description: 'A vibrant template with a touch of color, unique layout, and playful elements.',
    component: CreativeTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/creative/300/200',
    isPremium: false,
  },
  {
    id: 'corporate',
    name: 'Corporate Blue',
    description: 'A professional and structured design with a corporate blue header and clear sections.',
    component: CorporateTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/corporateblue/300/200',
    isPremium: false,
  },
  {
    id: 'tech',
    name: 'Tech Gradient',
    description: 'A modern, sleek design with gradient accents, suitable for tech-savvy businesses.',
    component: TechTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/techgradient/300/200',
    isPremium: true,
  },
  {
    id: 'elegant',
    name: 'Elegant Serif',
    description: 'A refined and sophisticated layout with classic typography and a luxurious feel.',
    component: ElegantTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/elegantserif/300/200',
    isPremium: true,
  },
  {
    id: 'natureharmony',
    name: "Nature's Harmony",
    description: 'A calm and organic design with earthy tones and a nature-inspired background.',
    component: NatureHarmonyTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/natureharmony/300/200',
    isPremium: true,
  },
  {
    id: 'geometricpulse',
    name: 'Geometric Pulse',
    description: 'A bold and modern template featuring abstract geometric patterns and sharp lines.',
    component: GeometricPulseTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/geometricpulse/300/200',
    isPremium: true,
  },
  {
    id: 'vintagescroll',
    name: 'Vintage Scroll',
    description: 'A classic template mimicking an old parchment with serif fonts and ornamental details.',
    component: VintageScrollTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/vintagescroll/300/200',
    isPremium: true,
  },
  {
    id: 'cosmicflow',
    name: 'Cosmic Flow',
    description: 'A futuristic design with a dark, space-themed background and glowing accents.',
    component: CosmicFlowTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/cosmicflow/300/200',
    isPremium: true,
  },
  {
    id: 'artdeco',
    name: 'Art Deco Elegance',
    description: 'Sophisticated geometric patterns with gold and black accents for a luxurious 1920s feel.',
    component: ArtDecoTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/artdeco/300/200',
    isPremium: true,
  },
  {
    id: 'rusticcharm',
    name: 'Rustic Charm',
    description: 'Warm, earthy tones with textures like wood or burlap, and handwritten-style fonts.',
    component: RusticCharmTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/rusticcharm/300/200',
    isPremium: false,
  },
  {
    id: 'watercolorwash',
    name: 'Watercolor Wash',
    description: 'Soft, blended watercolor backgrounds with light, airy typography for an artistic touch.',
    component: WatercolorWashTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/watercolor/300/200',
    isPremium: true,
  },
  {
    id: 'monochromefocus',
    name: 'Monochrome Focus',
    description: 'A stark and impactful black and white design, optionally with a single bold accent color.',
    component: MonochromeFocusTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/monochrome/300/200',
    isPremium: false,
  },
  {
    id: 'industrialgrit',
    name: 'Industrial Grit',
    description: 'Dark grays, metallic textures (simulated), and strong block or stencil fonts.',
    component: IndustrialGritTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/industrial/300/200',
    isPremium: true,
  },
  {
    id: 'bohemiandream',
    name: 'Bohemian Dream',
    description: 'Earthy tones, floral or paisley motifs, and flowing script fonts for a free-spirited vibe.',
    component: BohemianDreamTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/bohemian/300/200',
    isPremium: true,
  },
  {
    id: 'retropixel',
    name: 'Retro Pixel Gamer',
    description: '8-bit pixel art elements, classic video game fonts, and bright, contrasting colors.',
    component: RetroPixelTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/retropixel/300/200',
    isPremium: true,
  },
  {
    id: 'luxurygold',
    name: 'Luxury Gold Leaf',
    description: 'Deep, rich backgrounds (black, navy) with elegant gold foil-like accents and serif fonts.',
    component: LuxuryGoldTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/luxurygold/300/200',
    isPremium: true,
  },
  {
    id: 'custom',
    name: 'Fully Customizable',
    description: 'A flexible template where you control the colors, fonts, and layout. Make it truly yours.',
    component: CustomTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/custom/300/200',
    isPremium: true,
  },
  {
    id: 'swiss',
    name: 'Swiss Modern',
    description: 'Ultra-clean, minimalist design focusing on typography and whitespace for a sharp, professional look.',
    component: SwissModernTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/swiss/300/200',
    isPremium: false,
  },
  {
    id: 'sketch',
    name: 'Hand-Drawn Sketch',
    description: 'Charming and friendly, uses handwritten fonts and doodle-like elements for a personal touch.',
    component: HandDrawnSketchTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/sketch/300/200',
    isPremium: false,
  },
  {
    id: 'floral',
    name: 'Floral Botanical',
    description: 'Elegant and sophisticated, featuring delicate floral illustrations and graceful script fonts.',
    component: FloralBotanicalTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/floral/300/200',
    isPremium: true,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Glitch',
    description: 'A futuristic, high-tech design with neon accents and a cool, retro-digital vibe.',
    component: CyberpunkGlitchTemplate,
    thumbnailUrl: 'https://picsum.photos/seed/cyberpunk/300/200',
    isPremium: true,
  },
];