// A list of common world currencies for the selection dropdown.
export const CURRENCY_OPTIONS = [
    { value: 'USD', label: 'USD - United States Dollar' },
    { value: 'EUR', label: 'EUR - Euro' },
    { value: 'JPY', label: 'JPY - Japanese Yen' },
    { value: 'GBP', label: 'GBP - British Pound' },
    { value: 'AUD', label: 'AUD - Australian Dollar' },
    { value: 'CAD', label: 'CAD - Canadian Dollar' },
    { value: 'CHF', label: 'CHF - Swiss Franc' },
    { value: 'CNY', label: 'CNY - Chinese Yuan' },
    { value: 'INR', label: 'INR - Indian Rupee' },
    { value: 'BRL', label: 'BRL - Brazilian Real' },
    { value: 'RUB', label: 'RUB - Russian Ruble' },
    { value: 'KRW', label: 'KRW - South Korean Won' },
    { value: 'SGD', label: 'SGD - Singapore Dollar' },
    { value: 'MXN', label: 'MXN - Mexican Peso' },
    { value: 'NZD', label: 'NZD - New Zealand Dollar' },
    { value: 'HKD', label: 'HKD - Hong Kong Dollar' },
    { value: 'NOK', label: 'NOK - Norwegian Krone' },
    { value: 'SEK', label: 'SEK - Swedish Krona' },
    { value: 'TRY', label: 'TRY - Turkish Lira' },
    { value: 'ZAR', label: 'ZAR - South African Rand' },
    { value: 'PLN', label: 'PLN - Polish Złoty' },
    { value: 'THB', label: 'THB - Thai Baht' },
    { value: 'IDR', label: 'IDR - Indonesian Rupiah' },
    { value: 'HUF', label: 'HUF - Hungarian Forint' },
    { value: 'CZK', label: 'CZK - Czech Koruna' },
    { value: 'ILS', label: 'ILS - Israeli New Shekel' },
    { value: 'CLP', label: 'CLP - Chilean Peso' },
    { value: 'PHP', label: 'PHP - Philippine Peso' },
    { value: 'AED', label: 'AED - UAE Dirham' },
    { value: 'COP', label: 'COP - Colombian Peso' },
    { value: 'SAR', label: 'SAR - Saudi Riyal' },
    { value: 'MYR', label: 'MYR - Malaysian Ringgit' },
    { value: 'RON', label: 'RON - Romanian Leu' },
];
